version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: [ "changelog:dependencies" ]
    # Groups are updated together in one pull request
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
      otel-collector:
        patterns:
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/o*-collector-contrib/*"
      otel-instrumentation:
        patterns:
          - "go.opentelemetry.io/contrib/instrumentation/*"

  - package-ecosystem: gomod
    directory: "/internal/tools"
    schedule:
      interval: daily
    labels: [ "changelog:dependencies" ]

  - package-ecosystem: docker
    directories:
      - /cmd/agent
      - /cmd/all-in-one
      - /cmd/anonymizer
      - /cmd/collector
      - /cmd/es-index-cleaner
      - /cmd/ingester
      - /cmd/jaeger
      - /cmd/query
      - /cmd/remote-storage
      - /cmd/tracegen
      - /crossdock
      - /docker/base
      - /docker/debug
      - /examples/hotrod
      - /plugin/storage/cassandra
    schedule:
      interval: daily
  - package-ecosystem: docker
    directories:
      - /docker-compose/elasticsearch/v7
      - /docker-compose/elasticsearch/v8
    schedule:
      interval: daily
    ignore:
      - dependency-name: "docker.elastic.co/elasticsearch/elasticsearch"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: docker
    directories:
      - /docker-compose/opensearch/v1
      - /docker-compose/opensearch/v2
    schedule:
      interval: daily
    ignore:
      - dependency-name: "opensearchproject/opensearch"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: docker
    directory: /docker-compose/kafka-integration-test
    schedule:
      interval: daily
    ignore:
      - dependency-name: "bitnami/kafka"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: docker
    directories:
      - /docker-compose/cassandra/v4
      - /docker-compose/cassandra/v5
    schedule:
      interval: daily
    ignore:
      - dependency-name: "cassandra"
        update-types: [ "version-update:semver-major" ]
