site_name: Jaeger
edit_uri: edit/master/docs/
theme_dir: docs/theme
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
site_favicon: 'images/favicon.ico'
repo_name: 'uber/jaeger'
repo_url: 'https://github.com/uber/jaeger'
extra:
  logo: 'images/jaeger-logo.png'
pages: 
  - 'index.md'
  - 'Getting Started' : 'getting_started.md'
  - 'Architecture' : 'architecture.md'
