services:
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT:-}
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    ports:
      - "16686:16686"

  otel_collector:
    networks:
      backend:
        # This is the host name used in Prometheus scrape configuration.
        aliases: [spm_metrics_source]
    image: otel/opentelemetry-collector-contrib:${OTEL_IMAGE_TAG:-0.112.0}
    volumes:
      - ${OTEL_CONFIG_SRC:-./otel-collector-config-connector.yml}:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger
    ports:
      - "8889:8889"

  microsim:
    networks:
      - backend
    image: yurishkuro/microsim:v0.6.0@sha256:fd75a9b3dd1bb4d7d305a562edeac60051a7fec784b898ff7ab834eacc73f41e
    command: "-d 24h -s 500ms"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel_collector:4318
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - otel_collector

  prometheus:
    networks:
      - backend
    image: prom/prometheus:v3.9.1@sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

networks:
  backend:
