global:
  
  # Set low scrape and evaluation intervals to speed up e2e test 
  scrape_interval:     5s # Default is every 15sec
  evaluation_interval: 5s # Default is every 15sec

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
    - targets: ['spm_metrics_source:8889']
  - job_name: jaeger-collector-metrics
    static_configs:
    - targets: [ 'spm_metrics_source:8888' ]