$defs:
  config:
    type: object
    properties:
      multi_tenancy:
        $ref: github.com/jaegertracing/jaeger/internal/tenancy.options
      storage:
        type: string
    allOf:
      - $ref: go.opentelemetry.io/collector/config/configgrpc.server_config
