global:
  imageRegistry: docker.io

allInOne:
  enabled: true
  image:
    pullPolicy: Always
  extraEnv: []
  

# Enable HotROD demo application
hotrod:
  enabled: true
  image:
    tag: "1.72.0"
  args:
    - all
  extraArgs:
    - --jaeger-ui=https://jaeger.demo.jaegertracing.io
    - --otel-exporter=otlp
  livenessProbe:
    path: /
  readinessProbe:
    path: /
  extraEnv:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://jaeger:4318
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: http://jaeger:4318/v1/traces
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_SERVICE_NAME
      value: hotrod-frontend
  

query:
  service:
    type: ClusterIP
