services:
    jaeger:
      image: cr.jaegertracing.io/jaegertracing/jaeger:latest@sha256:b585df1b6299bbbd16bf7c679da30389349736e4b6bc8f4f500142a75bf26ca8 # v2.12.0
      ports:
        - '16686:16686'
        - '4318:4318'

    tracegen:
      image: cr.jaegertracing.io/jaegertracing/jaeger-tracegen:latest@sha256:3c1891b832c9a335f5588ed1b153c853f5217740ac562bf827c6bc661a1412d4
      environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      command: ["-duration", "10s", "-workers", "3", "-pause", "250ms"]
      depends_on:
        - jaeger
