service:
  extensions: [jaeger_storage, jaeger_query, remote_storage, remote_storage/archive, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8887
    logs:
      level: debug
    # TODO Initialize telemetry tracer once OTEL released new feature.
    # https://github.com/open-telemetry/opentelemetry-collector/issues/10663

extensions:
  healthcheckv2:
    use_v2: true
    http:
      # use different port to avoid conflict with collector on 13133
      endpoint: 0.0.0.0:12133

  jaeger_query:
    storage:
      traces: some-storage
      traces_archive: another-storage
    ui:
      config_file: ./cmd/jaeger/config-ui.json
    grpc:
      endpoint: "${env:JAEGER_QUERY_GRPC_ENDPOINT:-localhost:16685}"
    http:
      endpoint: "${env:JAEGER_QUERY_HTTP_ENDPOINT:-localhost:16686}"
  jaeger_storage:
    backends:
      some-storage:
        memory:
          max_traces: 100000
      another-storage:
        memory:
          max_traces: 100000
  remote_storage:
    endpoint: localhost:17271
    storage: some-storage
  remote_storage/archive:
    endpoint: localhost:17272
    storage: another-storage

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some-storage
