name: CIT Cassandra

on:
  workflow_call:

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  cassandra:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jaeger-version: [v1, v2]
        create-schema: [manual, auto]
        version:
        - distribution: cassandra
          major: 4.x
          schema: v004
        - distribution: cassandra
          major: 5.x
          schema: v004
        exclude:
        # Exclude v1 as create schema on fly is available for v2 only
        - jaeger-version: v1
          create-schema: auto
    name: ${{ matrix.version.distribution }}-${{ matrix.version.major }} ${{ matrix.jaeger-version }} schema=${{ matrix.create-schema }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: 1.26.x

    - name: Run cassandra integration tests
      id: test-execution
      run: bash scripts/e2e/cassandra.sh ${{ matrix.version.major }} ${{ matrix.version.schema }} ${{ matrix.jaeger-version }}
      env:
        SKIP_APPLY_SCHEMA: ${{ matrix.create-schema == 'auto' && true || false }}
     
    - uses: ./.github/actions/verify-metrics-snapshot
      if: matrix.jaeger-version == 'v2'
      with:
        snapshot: metrics_snapshot_cassandra
        artifact_key: metrics_snapshot_cassandras_${{ matrix.version.major }}_${{ matrix.version.schema }}_${{ matrix.jaeger-version }}_${{ matrix.create-schema }}

    - name: Upload coverage to codecov
      uses: ./.github/actions/upload-codecov
      with:
        files: cover.out
        flags: cassandra-${{ matrix.version.major }}-${{ matrix.jaeger-version }}-${{ matrix.create-schema }}
    
    
