name: CIT gRPC

on:
  workflow_call:

concurrency:
  group: cit-grpc-${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  grpc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [v1, v2]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: 1.24.x

    - name: Run gRPC storage integration tests
      run: |
        case ${{ matrix.version }} in
          v1)
            SPAN_STORAGE_TYPE=memory make grpc-storage-integration-test
            ;;
          v2)
            STORAGE=grpc SPAN_STORAGE_TYPE=memory make jaeger-v2-storage-integration-test
            ;;
        esac

    - uses: ./.github/actions/verify-metrics-snapshot
      if: matrix.version == 'v2'
      with:
        snapshot: metrics_snapshot_grpc
        artifact_key: metrics_snapshot_grpc_${{ matrix.version }}

    - name: Upload coverage to codecov
      uses: ./.github/actions/upload-codecov
      with:
        files: cover.out
        flags: grpc_${{ matrix.version }}
