name: CIT Badger

on:
  workflow_call:

concurrency:
  group: cit-badger-${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  badger:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [v1, v2]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: 1.24.x

    - name: Run Badger storage integration tests
      run: |
        case ${{ matrix.version }} in
          v1)
            make badger-storage-integration-test
            ;;
          v2)
            STORAGE=badger make jaeger-v2-storage-integration-test
            ;;
        esac

    - uses: ./.github/actions/verify-metrics-snapshot
      if: matrix.version == 'v2'
      with:
        snapshot: metrics_snapshot_badger
        artifact_key: metrics_snapshot_badger_${{ matrix.version }}
  
    - name: Upload coverage to codecov
      uses: ./.github/actions/upload-codecov
      with:
        files: cover.out
        flags: badger_${{ matrix.version }}
