name: CIT Badger

on:
  workflow_call:

concurrency:
  group: cit-badger-${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  badger:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [v1, v2]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: 1.25.x

    - name: Run Badger storage integration tests
      run: |
        case ${{ matrix.version }} in
          v1)
            make badger-storage-integration-test
            ;;
          v2)
            STORAGE=badger make jaeger-v2-storage-integration-test
            ;;
        esac

    - uses: ./.github/actions/verify-metrics-snapshot
      if: matrix.version == 'v2'
      with:
        snapshot: metrics_snapshot_badger
        artifact_key: metrics_snapshot_badger_${{ matrix.version }}
  
    - name: Upload coverage to codecov
      uses: ./.github/actions/upload-codecov
      with:
        files: cover.out
        flags: badger_${{ matrix.version }}
