name: Publish release

on:
  release:
    types:
      - published

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        go-version: 1.19.x

    - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: '16'

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build binaries
      id: build-binaries
      run: make build-all-platforms

    - name: Package binaries
      id: package-binaries
      run: bash scripts/package-deploy.sh
      if: steps.build-binaries.outcome == 'success'

    - name: Upload binaries
      uses: svenstaro/upload-release-action@133984371c30d34e38222a64855679a414cb7575
      with:
        file: '{deploy/*.tar.gz,deploy/*.zip,deploy/*.sha256sum.txt}'
        file_glob: true
        tag: ${{ github.ref }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.package-binaries.outcome == 'success'

    - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18

    - name: Build and upload all docker images
      run: bash scripts/build-upload-docker-images.sh
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Build, test, and publish all-in-one image
      run: bash scripts/build-all-in-one-image.sh
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Build, test, and publish hotrod image
      run: bash scripts/hotrod-integration-test.sh
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: SBOM Generation
      uses: anchore/sbom-action@b7e8507c6a3c89b7099a0198366d862c8f3ad8f1
      with:
        artifact-name: jaeger-SBOM.spdx.json
