name: Unit Tests on Go Tip

on:
  push:
    branches: [main]

  # We normally don't want this workflow to run on PRs, only on main branch.
  # But to allow testing of this workflow itself, add `run-all-workflows` label.
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-tests-go-tip:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run-all-workflows')
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up stable Go for tools
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: 1.25.x

    - name: Install test deps
      # even though the same target runs from test-ci, running it separately makes for cleaner log in GH workflow
      run: make install-test-tools

    - name: Install Go Tip
      uses: ./.github/actions/setup-go-tip
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run unit tests
      run: make test-ci

    - name: Lint
      run: echo skip linting on Go tip
