# Fake "DCO check" workkflow inspired by https://github.com/onnx/onnx/pull/5398/files.
# The regular DCO check is required, but it does not run from a merge queue and there is
# no way to configure it to run.
name: DCO
on:
  merge_group:

permissions:  
  contents: read
jobs:
  DCO:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fake DCO check to avoid blocking the merge queue"